#pragma once

//#define USE_MATRIX_I2C

#define MASTER_RIGHT

#define TAPPING_TERM 300

#ifdef RGB_MATRIX_ENABLE
#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_SLEEP

#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#endif
