LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no

RGB_MATRIX_ENABLE = yes
RGBLIGHT_ENABLE = no
BLUETOOTH_ENABLE = no
AUDIO_ENABLE = no
OLED_DRIVER_ENABLE = yes

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = no
WPM_ENABLE = yes
